[package]
name = "yew_example"
version = "0.1.0"
edition = "2021"

[dependencies]
yew = { workspace = true, features = ["csr"] }
rustflare = { path = "../../rustflare", features = ["yew"] }
wasm-bindgen = "0.2.93"
