[package]
name = "yew_example"
edition.workspace = true
version.workspace = true
authors.workspace = true
description.workspace = true

[dependencies]
yew = { workspace = true, features = ["csr"] }
rustflare = { path = "../../rustflare", features = ["yew"] }
wasm-bindgen = "0.2.93"
